// const loadEvents = async () => {
//   const eventFull = await fetch('http://192.168.1.65:8000/get_events/', {
//     method: 'GET',
//   });
//   console.log(eventFull);
// };
// loadEvents();

export const loadEvents = [
  {
    id: 653296,
    time_type: 1,
    date: '2024-01-01 18:00:00',
    fix_date: '2024-01-01 18:00:00',
    end_date: '2024-01-01 18:00:00',
    timestamp: 1704121200,
    timezone: 'Europe/Moscow',
    name: 'Щелкунчик. Театр балета им. Л. Якобсона',
    show_id: 93393,
    is_pushkin: true,
    location_id: 138043,
    location_name: 'Александринский театр (Основная сцена)',
    service_name: 'Основная сцена (2022 новая)',
    count: 0,
    min_price: '0.00',
    max_price: '0.00',
    image:
      'https://store.rambler.ru/tickets/images/shows/2023/xO61mOfRcJRo129TSyayrTMbTcEu0LthYCpNOOhc.jpg',
    age_limit: 6,
    desc: '',
    only_private_sells: false,
    show_categories: [],
    is_season: false,
    is_covid_free: false,
    is_hide_time: false,
    building: {
      id: 674,
      name: 'Александринский театр',
      city_id: 2,
      address: 'Россия, Санкт-Петербург, площадь Островского, 6 ',
      lat: '59.931774',
      lon: '30.336278',
    },
    pipeline_event_id: 0,
    is_access_only_link: false,
  },
  {
    id: 679959,
    time_type: 1,
    date: '2024-01-01 19:00:00',
    fix_date: '2024-01-01 19:00:00',
    end_date: '2024-01-01 19:00:00',
    timestamp: 1704124800,
    timezone: 'Europe/Moscow',
    name: 'Временная экспозиция',
    show_id: 61939,
    is_pushkin: false,
    location_id: 138612,
    location_name: 'Александринский театр (Основная сцена)',
    service_name: 'Основная сцена (входные билеты для экскурсии)',
    count: 0,
    min_price: '0.00',
    max_price: '0.00',
    image: '/img/gag.jpg',
    age_limit: 6,
    desc: '',
    only_private_sells: false,
    show_categories: [],
    is_season: false,
    is_covid_free: false,
    is_hide_time: false,
    building: {
      id: 674,
      name: 'Александринский театр',
      city_id: 2,
      address: 'Россия, Санкт-Петербург, площадь Островского, 6 ',
      lat: '59.931774',
      lon: '30.336278',
    },
    pipeline_event_id: 0,
    is_access_only_link: false,
  },
  {
    id: 680314,
    time_type: 1,
    date: '2024-01-01 19:00:00',
    fix_date: '2024-01-01 19:00:00',
    end_date: '2024-01-01 19:00:00',
    timestamp: 1704124800,
    timezone: 'Europe/Moscow',
    name: 'Временная экспозиция ( 3 ярус) ',
    show_id: 64703,
    is_pushkin: false,
    location_id: 138721,
    location_name: 'Александринский театр (Основная сцена)',
    service_name: 'Основная сцена (основной и льготный)',
    count: 0,
    min_price: '0.00',
    max_price: '0.00',
    image: '/img/gag.jpg',
    age_limit: 6,
    desc: '',
    only_private_sells: false,
    show_categories: [],
    is_season: false,
    is_covid_free: false,
    is_hide_time: false,
    building: {
      id: 674,
      name: 'Александринский театр',
      city_id: 2,
      address: 'Россия, Санкт-Петербург, площадь Островского, 6 ',
      lat: '59.931774',
      lon: '30.336278',
    },
    pipeline_event_id: 0,
    is_access_only_link: false,
  },
];
